# Generated by Django 4.2.1 on 2023-05-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_plantas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='plantas',
            field=models.ManyToManyField(related_name='projetos', to='app_plantas.plantas'),
        ),
    ]
