from django.db import models

# Create your models here.
class Plantas(models.Model):
    id_planta = models.AutoField(primary_key=True)
    especie= models.TextField(max_length=256)
    nome_popular= models.TextField(max_length=256)
    sinonimia= models.TextField(max_length=256)
    familia= models.TextField(max_length=256)
    bioma= models.TextField(max_length=256)
    formacao_vegetal= models.TextField(max_length=51)
    fitofisionomias= models.TextField(max_length=512)
    presenca_nos_estados= models.TextField(max_length=256)
    risco_extincao= models.TextField(max_length=51)
    periodo_coleta_sementes= models.TextField(max_length=51)
    beneficiamento_sementes= models.TextField(max_length=512)
    porcentagem_germinacao= models.TextField(max_length=51)
    substrato_muda= models.TextField(max_length=512)
    desenvolvimento_muda_viveiro= models.TextField(max_length=512)
    numero_sementes_kg= models.TextField(max_length=51)
    armazenamento= models.TextField(max_length=512)
    semeadura= models.TextField(max_length=512)
    nivel_sombreamento_muda_viveiro= models.TextField(max_length=512)
    tolerancia_sombra= models.TextField(max_length=512)
    estrategia_ecologica_ocupacao= models.TextField(max_length=512)
    desenvolvimento_muda_campo= models.TextField(max_length=512)
    recomendacao_adubacao_plantio_campo= models.TextField(max_length=512)
    porte_da_planta= models.TextField(max_length=51)
    periodo_floracao= models.TextField(max_length=512)
    periodo_frutificacao= models.TextField(max_length=512)
    uso_economico= models.TextField(max_length=51)
    caduciflora= models.TextField(max_length=51)
    polinizacao= models.TextField(max_length=51)
    dispersao= models.TextField(max_length=51)

class Projetos(models.Model):
    id_projeto = models.AutoField(primary_key=True)
    nome = models.TextField(max_length=100)
    descricao = models.TextField(max_length=1024)
    plantas = models.ManyToManyField(Plantas, related_name="projetos")